name: Pipeline-Fallbeispiel-main

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deploy job
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: release.zip
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.Client_ID }}
          tenant-id: ${{ secrets.Tenant_ID }}
          subscription-id: ${{ secrets.Subscription_ID }}
      - name: 'DeployAzure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'InflusGoofs'
          slot-name: 'Production'
          package: .
