name: Pipeline-Fallbeispiel-Main

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v1
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.Client_ID }}
          tenant-id: ${{ secrets.Tenant_ID }}
          subscription-id: ${{ secrets.Subscription_ID }}
      - name: 'DeployAzure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'InflusGoofs'
          slot-name: 'Production'
          package: .
